
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'kc_shs'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'hubods_test'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

seeds:
  kc_shs:
    +schema: dbt_seed
    generated:
      connector_configs:
        +column_types:
          JobName: varchar(255)
          ConnectorName: varchar(255)
          ConnectorType: varchar(50)
          IsActive: bit
          Level: int
          ConfigTemplate: nvarchar(max)
          ConfigId: varchar(255)
      topic_lag_job_configs:
        +column_types:
          ConnectorReference: varchar(255)
          TopicName: varchar(255)
          IsActive: bit
# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  kc_shs:
    staging:
      +materialized: view
