CREATE TABLE [ingest_reference].[dbo].[TopicLagLogs] (
  [Id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
  [TopicLagJobId] UNIQUEIDENTIFIER NULL,
  [ConnectorId] UNIQUEIDENTIFIER NULL,
  [JobName] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  [ConnectorName] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  [TopicName] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  [EndOffset] BIGINT NULL,
  [EventStatus] VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  [Message] NVARCHAR(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  [Details] NVARCHAR(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL DEFAULT N'{}',
  [CreatedAt] DATETIMEOFFSET(3) NOT NULL DEFAULT SYSDATETIMEOFFSET(),
  CONSTRAINT [PK_TopicLagLogs] PRIMARY KEY ([Id])
);

CREATE NONCLUSTERED INDEX [TopicLagLogs.IDX_01]
ON [ingest_reference].[dbo].[TopicLagLogs] (
  [CreatedAt] DESC,
  [ConnectorId] ASC,
  [TopicLagJobId] ASC,
  [EventStatus] ASC
)
INCLUDE ([ConnectorName], [TopicName], [Details])
WITH
  (
    PAD_INDEX = OFF,
    FILLFACTOR = 100,
    SORT_IN_TEMPDB = OFF,
    IGNORE_DUP_KEY = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    ONLINE = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY];
