
version: 2

models:
  - name: stg_connectors
    columns:
      # 1. Test cột id: Không được NULL và không được trùng
      - name: id
#        tests:
#          - not_null
#          - unique

      # 2. Test cột IsActive: BẮT BUỘC chỉ được chứa giá trị 0 hoặc 1
      - name: IsActive
#        tests:
#          - accepted_values:
#              values: [0, 1]

      # 2. cột Level: BẮT BUỘC chỉ được chứa giá trị từ 1 đến 4
      - name: Level
#        tests:
#          - accepted_values:
#              values: [1, 4]

