USE [ingest_reference];

INSERT INTO dbo.Connectors (
    JobName, ConnectorName, ConnectorType, IsActive, Level, ConfigTemplate, ConfigId
)
VALUES (
    'TOPO-CLI-G038',
    'TOPO-CLI-G038',
    'source',
    1,
    4,
    N'{
  "connector.class": "io.debezium.connector.oracle.OracleConnector",
  "message.key.columns": "TOPOVN.CHARGE_CODES:CHARGE_CD,PAYMENT_METHOD;TOPOVN.PREGATE_REEFER:EIR_ID;TOPOVN.DISCHARGE_LIST_COMMENTS:MANIFEST_KEY,COMMENTS,COMMENT_SEQ;TOPOVN.CONVERT_ISO:ORIGINAL_ISO,ISO,LINE_OPER;TOPOVN.SEAL_MANAGEMENT_MASTER:ID;TOPOVN.PREGATE_TRANSACT:EIR_ID,ITEM_KEY;TOPOVN.CONVERT_TO_ISO:ISO;TOPOVN.RA_SPECIFIC_CTRS:RA_KEY;TOPOVN.DISCHARGE_LIST:MANIFEST_KEY;TOPOVN.ITEM_STRIP_STUFF:STUSTR_EIR_ID;TOPOVN.FREE_RULES:ID;TOPOVN.CONFIG_STOPCODE:STOP_CODE;TOPOVN.PORTCODE:PORT;TOPOVN.DAMAGE_CODE:DAMAGE_CD;TOPOVN.CTNR_MOVE_REG_MASTER:REG_ID;TOPOVN.RA_MTY:RA_KEY;TOPOVN.RA_COMMON:RAC_KEY;TOPOVN.CONTAINER_STRUCTURE:ITEM_NO;TOPOVN.ITEM_CHARGES:ID;TOPOVN.CHE_MASTER:CHE_ID,INTERNAL_CHE_ID;TOPOVN.GATE_NO_INFO:GATE_NO;TOPOVN.EMPTY_RECEIV_DETAIL:RA_KEY,ITEM_NO;TOPOVN.GATE_LANE_INFO:GATE_NO,LANE_NO;TOPOVN.AGENT:AGENT,EXPIRY_TS,LINE_OPER,IS_CONT_AGENT,IS_BILL_AGENT",
  "max.queue.size": "16384",
  "topic.creation.default.partitions": "3",
  "timestampConverter.format.date": "yyyy-MM-dd HH:mm:ss",
  "schema.include.list": "TOPOVN",
  "log.mining.transaction.retention.ms": "3600000",
  "log.mining.sleep.time.min.ms": "0",
  "log.mining.strategy": "online_catalog",
  "buffer.memory": "67108864",
  "include.schema.changes": "true",
  "schema.history.internal.store.only.captured.tables.ddl": "true",
  "tombstones.on.delete": "false",
  "topic.prefix": "CDC.TOPO-CLI",
  "decimal.handling.mode": "double",
  "schema.history.internal.kafka.topic": "schemahistory.TOPO-CLI-G035",
  "timestampConverter.format.datetime": "yyyy-MM-dd HH:mm:ss",
  "topic.creation.default.replication.factor": "3",
  "converters": "timestampConverter",
  "value.converter": "org.apache.kafka.connect.json.JsonConverter",
  "log.mining.sleep.time.max.ms": "3000",
  "log.mining.scn.gap.detection.gap.size.min": "1000000",
  "database.user": "APP_BIGDATA",
  "database.dbname": "TOPOVN",
  "timestampConverter.debug": "false",
  "timestampConverter.type": "oryanmoshe.kafka.connect.util.TimestampConverter",
  "log.mining.batch.size.max": "100000",
  "database.connection.adapter": "logminer_unbuffered",
  "log.mining.sleep.time.default.ms": "1000",
  "log.mining.buffer.type": "memory",
  "database.url": "{url}",
  "timestampConverter.format.time": "HH:mm:ss",
  "log.mining.view.fetch.size": "1000",
  "schema.history.internal.kafka.bootstrap.servers": "{kafka_server}",
  "event.processing.failure.handling.mode": "warn",
  "log.mining.batch.size.increment": "40000",
  "schema.history.internal.skip.unparseable.ddl": "true",
  "topic.creation.enable": "true",
  "log.mining.query.filter.mode": "in",
  "database.password": "{pwd}",
  "log.mining.batch.size.min": "10000",
  "value.converter.schemas.enable": "false",
  "log.mining.batch.size.default": "40000",
  "name": "TOPO-CLI-G038",
  "max.batch.size": "8192",
  "table.include.list": "TOPOVN.DEV_DATA_AGENT,TOPOVN.AGENT,TOPOVN.CHARGE_CODES,TOPOVN.CHE_MASTER,TOPOVN.CONFIG_STOPCODE,TOPOVN.CONVERT_ISO,TOPOVN.CONVERT_TO_ISO,TOPOVN.CTNR_MOVE_REG_MASTER,TOPOVN.DAMAGE_CODE,TOPOVN.DISCHARGE_LIST,TOPOVN.EMPTY_RECEIV_DETAIL,TOPOVN.FREE_RULES,TOPOVN.GATE_LANE_INFO,TOPOVN.GATE_NO_INFO,TOPOVN.ITEM_CHARGES,TOPOVN.ITEM_STRIP_STUFF,TOPOVN.PORTCODE,TOPOVN.PREGATE_REEFER,TOPOVN.PREGATE_TRANSACT,TOPOVN.RA_COMMON,TOPOVN.RA_MTY,TOPOVN.RA_SPECIFIC_CTRS,TOPOVN.SEAL_MANAGEMENT_MASTER,TOPOVN.DISCHARGE_LIST_COMMENTS,TOPOVN.CONTAINER_STRUCTURE",
  "log.mining.scn.gap.detection.time.interval.max.ms": "10000",
  "snapshot.mode": "no_data"
}',
    '{config_id}'
);

INSERT INTO dbo.Connectors (
    JobName, ConnectorName, ConnectorType, IsActive, Level, ConfigTemplate, ConfigId
)
VALUES (
    'TOPO-CLI-G042',
    'TOPO-CLI-G042',
    'source',
    1,
    4,
    N'{
  "connector.class": "io.debezium.connector.oracle.OracleConnector",
  "message.key.columns": "TOPOVN.EDI_ITEM_PRE_ADVICE:ITEM_KEY;TOPOVN.LINE_OPER:LINE_OPER;TOPOVN.YARD_AREA:STACK,FR_DATE,TO_DATE;TOPOVN.ITEM_STOPS:ITEM_KEY,STOP_CD;TOPOVN.OPERATION_METHOD:OPERATION_METHOD;TOPOVN.ITEM_SPECIAL_HANDLING:ITEM_KEY,CODE;TOPOVN.ITEM_SEAL:ITEM_KEY,SEAL_TYPE,SEAL_NO,SITE_ID,SEAL_SEQ,SEAL_REMOVING_DATE,INVALID_SEAL;TOPOVN.VESSELS:VES_CD;TOPOVN.SYS_CODES:CODE_TP,CODE_REF;TOPOVN.ITEM_COMMENTS:ITEM_KEY,COMMENT_SEQ,CRT_TS;TOPOVN.VESSEL_DETAILS:VES_ID;TOPOVN.VES_SERVICE:VES_SERVICE,DISCH_PORT,SEQ_NO;TOPOVN.TRK_TRANSACT:EIR_ID,ITEM_KEY,TRK_KEY;TOPOVN.ITEM:ITEM_KEY;TOPOVN.SPECIAL_HDL_CODE:SPECIAL_HDL_CODE,SPECIAL_HDL_DESC;TOPOVN.INVOICE:INVOICE_NO,INTERNAL_BOOK_NUMBER;TOPOVN.TRUCK:TRK_KEY;TOPOVN.ITEM_REEFER:ITEM_KEY;TOPOVN.PREGATE:CHARGE_BATCH_ID",
  "max.queue.size": "16384",
  "topic.creation.default.partitions": "3",
  "timestampConverter.format.date": "yyyy-MM-dd HH:mm:ss",
  "schema.include.list": "TOPOVN",
  "log.mining.transaction.retention.ms": "900000",
  "log.mining.sleep.time.min.ms": "0",
  "log.mining.strategy": "online_catalog",
  "buffer.memory": "67108864",
  "include.schema.changes": "true",
  "schema.history.internal.store.only.captured.tables.ddl": "true",
  "tombstones.on.delete": "false",
  "topic.prefix": "CDC.TOPO-CLI",
  "decimal.handling.mode": "double",
  "schema.history.internal.kafka.topic": "schemahistory.TOPO-CLI-G036",
  "timestampConverter.format.datetime": "yyyy-MM-dd HH:mm:ss",
  "topic.creation.default.replication.factor": "3",
  "converters": "timestampConverter",
  "value.converter": "org.apache.kafka.connect.json.JsonConverter",
  "log.mining.sleep.time.max.ms": "3000",
  "log.mining.scn.gap.detection.gap.size.min": "1000000",
  "database.user": "${file:/opt/kafka-connect/secrets/topo-cli-credential.properties:db.username}",
  "database.dbname": "${file:/opt/kafka-connect/secrets/topo-cli-credential.properties:db.dbname}",
  "timestampConverter.debug": "false",
  "timestampConverter.type": "oryanmoshe.kafka.connect.util.TimestampConverter",
  "log.mining.batch.size.max": "100000",
  "database.connection.adapter": "logminer_unbuffered",
  "log.mining.sleep.time.default.ms": "1000",
  "log.mining.buffer.type": "memory",
  "database.url": "{url}",
  "timestampConverter.format.time": "HH:mm:ss",
  "log.mining.view.fetch.size": "1000",
  "schema.history.internal.kafka.bootstrap.servers": "{kafka_server}",
  "event.processing.failure.handling.mode": "warn",
  "log.mining.batch.size.increment": "40000",
  "schema.history.internal.skip.unparseable.ddl": "true",
  "topic.creation.enable": "true",
  "log.mining.query.filter.mode": "in",
  "database.password": "{pwd}",
  "log.mining.batch.size.min": "10000",
  "value.converter.schemas.enable": "false",
  "log.mining.batch.size.default": "40000",
  "name": "TOPO-CLI-G042",
  "max.batch.size": "8192",
  "table.include.list": "TOPOVN.INVOICE,TOPOVN.ITEM,TOPOVN.ITEM_COMMENTS,TOPOVN.ITEM_REEFER,TOPOVN.ITEM_SEAL,TOPOVN.ITEM_SPECIAL_HANDLING,TOPOVN.ITEM_STOPS,TOPOVN.LINE_OPER,TOPOVN.OPERATION_METHOD,TOPOVN.SPECIAL_HDL_CODE,TOPOVN.SYS_CODES,TOPOVN.TRK_TRANSACT,TOPOVN.TRUCK,TOPOVN.VES_SERVICE,TOPOVN.VESSEL_DETAILS,TOPOVN.VESSELS,TOPOVN.YARD_AREA,TOPOVN.EDI_ITEM_PRE_ADVICE,TOPOVN.PREGATE,TOPOVN.VESSEL_DETAILS_OPS,TOPOVN.CABLEHOOK_REQUEST,TOPOVN.CHE_COMPANY,TOPOVN.CHE_MASTER,TOPOVN.ITEM_COMMODITY,TOPOVN.THU_TUC_HAI_QUAN",
  "log.mining.scn.gap.detection.time.interval.max.ms": "10000",
  "snapshot.mode": "no_data"
}',
    '{config_id}'
);

INSERT INTO dbo.Connectors (
    JobName, ConnectorName, ConnectorType, IsActive, Level, ConfigTemplate, ConfigId
)
VALUES (
    'TOPO-CLI-G038',
    'TOPO-CLI-G038',
    'source',
    1,
    4,
    N'{
  "connector.class": "io.debezium.connector.oracle.OracleConnector",
  "message.key.columns": "TOPOVN.CHARGE_CODES:CHARGE_CD,PAYMENT_METHOD;TOPOVN.PREGATE_REEFER:EIR_ID;TOPOVN.DISCHARGE_LIST_COMMENTS:MANIFEST_KEY,COMMENTS,COMMENT_SEQ;TOPOVN.CONVERT_ISO:ORIGINAL_ISO,ISO,LINE_OPER;TOPOVN.SEAL_MANAGEMENT_MASTER:ID;TOPOVN.PREGATE_TRANSACT:EIR_ID,ITEM_KEY;TOPOVN.CONVERT_TO_ISO:ISO;TOPOVN.RA_SPECIFIC_CTRS:RA_KEY;TOPOVN.DISCHARGE_LIST:MANIFEST_KEY;TOPOVN.ITEM_STRIP_STUFF:STUSTR_EIR_ID;TOPOVN.FREE_RULES:ID;TOPOVN.CONFIG_STOPCODE:STOP_CODE;TOPOVN.PORTCODE:PORT;TOPOVN.DAMAGE_CODE:DAMAGE_CD;TOPOVN.CTNR_MOVE_REG_MASTER:REG_ID;TOPOVN.RA_MTY:RA_KEY;TOPOVN.RA_COMMON:RAC_KEY;TOPOVN.CONTAINER_STRUCTURE:ITEM_NO;TOPOVN.ITEM_CHARGES:ID;TOPOVN.CHE_MASTER:CHE_ID,INTERNAL_CHE_ID;TOPOVN.GATE_NO_INFO:GATE_NO;TOPOVN.EMPTY_RECEIV_DETAIL:RA_KEY,ITEM_NO;TOPOVN.GATE_LANE_INFO:GATE_NO,LANE_NO;TOPOVN.AGENT:AGENT,EXPIRY_TS,LINE_OPER,IS_CONT_AGENT,IS_BILL_AGENT",
  "max.queue.size": "16384",
  "topic.creation.default.partitions": "3",
  "timestampConverter.format.date": "yyyy-MM-dd HH:mm:ss",
  "schema.include.list": "TOPOVN",
  "log.mining.transaction.retention.ms": "3600000",
  "log.mining.sleep.time.min.ms": "0",
  "log.mining.strategy": "online_catalog",
  "buffer.memory": "67108864",
  "include.schema.changes": "true",
  "schema.history.internal.store.only.captured.tables.ddl": "true",
  "tombstones.on.delete": "false",
  "topic.prefix": "CDC.TOPO-CLI",
  "decimal.handling.mode": "double",
  "schema.history.internal.kafka.topic": "schemahistory.TOPO-CLI-G035",
  "timestampConverter.format.datetime": "yyyy-MM-dd HH:mm:ss",
  "topic.creation.default.replication.factor": "3",
  "converters": "timestampConverter",
  "value.converter": "org.apache.kafka.connect.json.JsonConverter",
  "log.mining.sleep.time.max.ms": "3000",
  "log.mining.scn.gap.detection.gap.size.min": "1000000",
  "database.user": "APP_BIGDATA",
  "database.dbname": "TOPOVN",
  "timestampConverter.debug": "false",
  "timestampConverter.type": "oryanmoshe.kafka.connect.util.TimestampConverter",
  "log.mining.batch.size.max": "100000",
  "database.connection.adapter": "logminer_unbuffered",
  "log.mining.sleep.time.default.ms": "1000",
  "log.mining.buffer.type": "memory",
  "database.url": "{url}",
  "timestampConverter.format.time": "HH:mm:ss",
  "log.mining.view.fetch.size": "1000",
  "schema.history.internal.kafka.bootstrap.servers": "{kafka_server}",
  "event.processing.failure.handling.mode": "warn",
  "log.mining.batch.size.increment": "40000",
  "schema.history.internal.skip.unparseable.ddl": "true",
  "topic.creation.enable": "true",
  "log.mining.query.filter.mode": "in",
  "database.password": "{pwd}",
  "log.mining.batch.size.min": "10000",
  "value.converter.schemas.enable": "false",
  "log.mining.batch.size.default": "40000",
  "name": "TOPO-CLI-G038",
  "max.batch.size": "8192",
  "table.include.list": "TOPOVN.DEV_DATA_AGENT,TOPOVN.AGENT,TOPOVN.CHARGE_CODES,TOPOVN.CHE_MASTER,TOPOVN.CONFIG_STOPCODE,TOPOVN.CONVERT_ISO,TOPOVN.CONVERT_TO_ISO,TOPOVN.CTNR_MOVE_REG_MASTER,TOPOVN.DAMAGE_CODE,TOPOVN.DISCHARGE_LIST,TOPOVN.EMPTY_RECEIV_DETAIL,TOPOVN.FREE_RULES,TOPOVN.GATE_LANE_INFO,TOPOVN.GATE_NO_INFO,TOPOVN.ITEM_CHARGES,TOPOVN.ITEM_STRIP_STUFF,TOPOVN.PORTCODE,TOPOVN.PREGATE_REEFER,TOPOVN.PREGATE_TRANSACT,TOPOVN.RA_COMMON,TOPOVN.RA_MTY,TOPOVN.RA_SPECIFIC_CTRS,TOPOVN.SEAL_MANAGEMENT_MASTER,TOPOVN.DISCHARGE_LIST_COMMENTS,TOPOVN.CONTAINER_STRUCTURE",
  "log.mining.scn.gap.detection.time.interval.max.ms": "10000",
  "snapshot.mode": "no_data"
}',
    '{config_id}'
);
