USE [ingest_reference];

INSERT INTO dbo.Connectors (
    JobName, ConnectorName, ConnectorType, IsActive, Level, ConfigTemplate, ConfigId
)
VALUES (
    'TOPO-TCH-G025',
    'TOPO-TCH-G025',
    'source',
    1,
    4,
    N'{
  "connector.class": "io.debezium.connector.oracle.OracleConnector",
  "compression.type": "gzip",
  "max.queue.size": "16384",
  "topic.creation.default.partitions": "1",
  "timestampConverter.format.date": "yyyy-MM-dd HH:mm:ss",
  "enable.idempotence": "true",
  "schema.include.list": "TOPOVN",
  "log.mining.transaction.retention.ms": "172800000",
  "delivery.timeout.ms": "600000",
  "retry.backoff.ms": "1000",
  "log.mining.strategy": "online_catalog",
  "buffer.memory": "67108864",
  "include.schema.changes": "true",
  "schema.history.internal.store.only.captured.tables.ddl": "true",
  "tombstones.on.delete": "false",
  "topic.prefix": "CDC.TOPO-TCH",
  "decimal.handling.mode": "double",
  "schema.history.internal.kafka.topic": "schemahistory.TOPO-TCH-G025",
  "timestampConverter.format.datetime": "yyyy-MM-dd HH:mm:ss",
  "topic.creation.default.replication.factor": "3",
  "converters": "timestampConverter",
  "value.converter": "org.apache.kafka.connect.json.JsonConverter",
  "max.in.flight.requests.per.connection": "5",
  "database.user": "APP_BIGDATA",
  "database.dbname": "TOPOVN",
  "timestampConverter.debug": "false",
  "timestampConverter.type": "oryanmoshe.kafka.connect.util.TimestampConverter",
  "request.timeout.ms": "300000",
  "log.mining.buffer.type": "memory",
  "acks": "all",
  "batch.size": "32768",
  "database.url": "{url}",
  "timestampConverter.format.time": "HH:mm:ss",
  "offset.flush.timeout.ms": "60000",
  "schema.history.internal.kafka.bootstrap.servers": "{kafka_server}",
  "event.processing.failure.handling.mode": "warn",
  "schema.history.internal.skip.unparseable.ddl": "true",
  "topic.creation.enable": "true",
  "retries": "10",
  "max.request.size": "2097152",
  "database.password": "{pwd}",
  "value.converter.schemas.enable": "false",
  "name": "TOPO-TCH-G025",
  "table.include.list": "TOPOVN.ITEM_LOCATION,TOPOVN.CTNR_MOVE_REG_DETAILS,TOPOVN.CUSTOMER,TOPOVN.ITEM_PTI,TOPOVN.DISCH_REEFER,TOPOVN.DISCH_SEAL,TOPOVN.DISCH_SPECIAL_HANDLING,TOPOVN.VES_ROTATION,TOPOVN.ITEM_DAMAGE,TOPOVN.VESSEL_DETAILS_OPS,TOPOVN.VES_ROTATION,TOPOVN.AGENT_CDC,TOPOVN.CUSTOMER_CDC",
  "max.batch.size": "4096",
  "snapshot.mode": "no_data"
}',
    '326'
);

INSERT INTO dbo.Connectors (
    JobName, ConnectorName, ConnectorType, IsActive, Level, ConfigTemplate, ConfigId
)
VALUES (
    'TOPO-TCH-G026',
    'TOPO-TCH-G026',
    'source',
    1,
    4,
    N'{
  "connector.class": "io.debezium.connector.oracle.OracleConnector",
  "compression.type": "gzip",
  "max.queue.size": "16384",
  "topic.creation.default.partitions": "1",
  "timestampConverter.format.date": "yyyy-MM-dd HH:mm:ss",
  "enable.idempotence": "true",
  "schema.include.list": "TOPOVN",
  "log.mining.transaction.retention.ms": "172800000",
  "delivery.timeout.ms": "600000",
  "retry.backoff.ms": "1000",
  "log.mining.strategy": "online_catalog",
  "buffer.memory": "67108864",
  "include.schema.changes": "true",
  "schema.history.internal.store.only.captured.tables.ddl": "true",
  "tombstones.on.delete": "false",
  "topic.prefix": "CDC.TOPO-TCH",
  "decimal.handling.mode": "double",
  "schema.history.internal.kafka.topic": "schemahistory.TOPO-TCH-G026",
  "timestampConverter.format.datetime": "yyyy-MM-dd HH:mm:ss",
  "topic.creation.default.replication.factor": "3",
  "converters": "timestampConverter",
  "value.converter": "org.apache.kafka.connect.json.JsonConverter",
  "max.in.flight.requests.per.connection": "5",
  "database.user": "APP_BIGDATA",
  "database.dbname": "TOPOVN",
  "timestampConverter.debug": "false",
  "timestampConverter.type": "oryanmoshe.kafka.connect.util.TimestampConverter",
  "request.timeout.ms": "300000",
  "log.mining.buffer.type": "memory",
  "acks": "all",
  "batch.size": "32768",
  "database.url": "{url}",
  "timestampConverter.format.time": "HH:mm:ss",
  "offset.flush.timeout.ms": "60000",
  "schema.history.internal.kafka.bootstrap.servers": "{kafka_server}",
  "event.processing.failure.handling.mode": "warn",
  "schema.history.internal.skip.unparseable.ddl": "true",
  "topic.creation.enable": "true",
  "retries": "10",
  "max.request.size": "2097152",
  "database.password": "{pwd}",
  "value.converter.schemas.enable": "false",
  "name": "TOPO-TCH-G026",
  "table.include.list": "TOPOVN.INVOICE,TOPOVN.ITEM,TOPOVN.ITEM_COMMENTS,TOPOVN.ITEM_REEFER,TOPOVN.ITEM_SEAL,TOPOVN.ITEM_SPECIAL_HANDLING,TOPOVN.ITEM_STOPS,TOPOVN.LINE_OPER,TOPOVN.OPERATION_METHOD,TOPOVN.SPECIAL_HDL_CODE,TOPOVN.SYS_CODES,TOPOVN.TRK_TRANSACT,TOPOVN.TRUCK,TOPOVN.VES_SERVICE,TOPOVN.VESSEL_DETAILS,TOPOVN.VESSELS,TOPOVN.YARD_AREA,TOPOVN.EDI_ITEM_PRE_ADVICE,TOPOVN.PREGATE",
  "max.batch.size": "4096",
  "snapshot.mode": "no_data"
}',
    '327'
);

INSERT INTO dbo.Connectors (
    JobName, ConnectorName, ConnectorType, IsActive, Level, ConfigTemplate, ConfigId
)
VALUES (
    'TOPO-TCH-G027',
    'TOPO-TCH-G027',
    'source',
    1,
    4,
    N'{
  "connector.class": "io.debezium.connector.oracle.OracleConnector",
  "topic.creation.default.partitions": "1",
  "transforms": "filterOldDeletes",
  "schema.include.list": "TOPOVN",
  "include.schema.changes": "true",
  "transforms.filterOldDeletes.filter.date.cutoff": "2025-01-01",
  "timestampConverter.format.datetime": "yyyy-MM-dd HH:mm:ss",
  "topic.creation.default.replication.factor": "3",
  "converters": "timestampConverter",
  "database.user": "APP_BIGDATA",
  "database.dbname": "TOPOVN",
  "request.timeout.ms": "300000",
  "acks": "all",
  "schema.history.internal.kafka.bootstrap.servers": "{kafka_server}",
  "schema.history.internal.skip.unparseable.ddl": "true",
  "topic.creation.enable": "true",
  "retries": "10",
  "database.password": "{pwd}",
  "value.converter.schemas.enable": "false",
  "name": "TOPO-TCH-G027",
  "max.batch.size": "4096",
  "snapshot.mode": "no_data",
  "compression.type": "gzip",
  "max.queue.size": "16384",
  "timestampConverter.format.date": "yyyy-MM-dd HH:mm:ss",
  "enable.idempotence": "true",
  "log.mining.transaction.retention.ms": "172800000",
  "delivery.timeout.ms": "600000",
  "retry.backoff.ms": "1000",
  "transforms.filterOldDeletes.filter.tables": "PREGATE_TRANSACT",
  "log.mining.strategy": "online_catalog",
  "buffer.memory": "67108864",
  "transforms.filterOldDeletes.filter.ops": "d",
  "schema.history.internal.store.only.captured.tables.ddl": "true",
  "tombstones.on.delete": "false",
  "topic.prefix": "CDC.TOPO-TCH",
  "decimal.handling.mode": "double",
  "schema.history.internal.kafka.topic": "schemahistory.TOPO-TCH-G027",
  "transforms.filterOldDeletes.filter.date.fields": "CRT_TS",
  "value.converter": "org.apache.kafka.connect.json.JsonConverter",
  "max.in.flight.requests.per.connection": "5",
  "timestampConverter.debug": "false",
  "timestampConverter.type": "oryanmoshe.kafka.connect.util.TimestampConverter",
  "transforms.filterOldDeletes.type": "com.example.smt.FilterDebeziumOpByDate",
  "log.mining.buffer.type": "memory",
  "batch.size": "32768",
  "database.url": "{url}",
  "timestampConverter.format.time": "HH:mm:ss",
  "offset.flush.timeout.ms": "60000",
  "event.processing.failure.handling.mode": "warn",
  "max.request.size": "2097152",
  "table.include.list": "TOPOVN.DEV_DATA_AGENT,TOPOVN.AGENT,TOPOVN.CHARGE_CODES,TOPOVN.CHE_MASTER,TOPOVN.CONFIG_STOPCODE,TOPOVN.CONVERT_ISO,TOPOVN.CONVERT_TO_ISO,TOPOVN.CTNR_MOVE_REG_MASTER,TOPOVN.DAMAGE_CODE,TOPOVN.DISCHARGE_LIST,TOPOVN.EMPTY_RECEIV_DETAIL,TOPOVN.FREE_RULES,TOPOVN.GATE_LANE_INFO,TOPOVN.GATE_NO_INFO,TOPOVN.ITEM_CHARGES,TOPOVN.ITEM_STRIP_STUFF,TOPOVN.PORTCODE,TOPOVN.PREGATE_REEFER,TOPOVN.PREGATE_TRANSACT,TOPOVN.RA_COMMON,TOPOVN.RA_MTY,TOPOVN.RA_SPECIFIC_CTRS,TOPOVN.SEAL_MANAGEMENT_MASTER,TOPOVN.DISCHARGE_LIST_COMMENTS,TOPOVN.CONTAINER_STRUCTURE"
}',
    '328'
);